### ISSUE TITLE
Design Docs Checklist

### ISSUE THREAD

**Issue by mkayys** [Izzy5021/NoodleOverflow#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [ ] Correctly formatted
    - [ ] each wiki page is listed in bullet points
    - [ ] all links route the correct page

## Comments

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://open.appacademy.io/learn/swe-in-person/full-stack-project/mvp-checklist) or they have clarified them with you
- [x] Contains a description sentence of the app
- [ ] Includes two to three detailed bullets on functionality and presentation of feature
- [ ] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [ ] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments
- hosting on Heroku won't take 2 days, probably 0.5 day; I suggest adding a day to ask questions and answer questions.
- Users can post questions to a problem? <-- in your 3rd MVP not sure what you mean
- please indicate which MVP is your CRUD feature
---

# Database Schema

- [ ] Contains correct datatypes
- [ ] Contains appropriate constraints/details
    - [ ] primary key
    - [ ] not null
    - [ ] unique
    - [ ] indexed
    - [ ] foreign key
- [ ] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [ ] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
- missing associations and questions can have a title/header then a body
- currently with your responses table, there's no way to know which question the response would be for
- upvote and downvote refer to a post_id but there is no posts table
- also you can comment on answers so will need another table
---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [ ] Correctly formatted
    - [ ] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
- format as JS and use VS code to create your state shape
- missing a curly bracket
---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [ ] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [ ] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
- refer to the following for formatting: https://github.com/appacademy/bluebird/wiki/backend-routes

- `GET /api/users` is for a users index page; for a single user's information, we need an id, so it would be `GET /api/users/:id`
- response and question in the route will be plural
- GET /api/question/:id - returns chirp <--- forgot to change, in the questions portion
---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [ ] Correctly formatted
    - [ ] Routes are displayed with `inline coding text` (backticks)

## Comments
- refer to the following for formatting: https://github.com/appacademy/bluebird/wiki/frontend-routes
- missing QuestionIndex, and what about answer components?
